### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by INotSleep** [xxr-mc/Knotty#1]
**When Knotty was relised ?)**

**Comment by Tapeline** [comment]
Never

**Comment by INotSleep** [comment]
Why?

**Comment by Tapeline** [comment]
> Why?

'cause **was** is past form of **to be** verb. It'll be released. Maybe.

**Comment by ExtraExtremeERA** [comment]
tbh even i don't know, currently i make other project that not so preferably to be open sourced and in parallel i learn some other things that will be helpful to knotty in future. I also plan to do knotty not fork from mohist/thermos and only fork directly from forge, because mohist and projects before it did some really weird stuff. And i wanna provide plugin support as a seperate forge mod, and knotty will be just optimised forge modloader and minecraft server itself. I think this architecture will be the most correct from clean code and just logically. Ok, so the direct answer on your question: in period from late spring to late summer or even later. nearby new year or earlier/later i start fully remake the architecture. (sorry for that late answer cuz i am really lazy)
